import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Header from "@/components/Header";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased dark`}
    >
      <body className="min-h-full flex flex-col bg-white dark:bg-black text-zinc-900 dark:text-zinc-50 mesh-gradient">
        <Header />
        <main className="flex-grow pt-24">{children}</main>
        <footer className="py-12 border-t border-zinc-200 dark:border-zinc-800">
          <div className="container mx-auto px-6 text-center text-sm text-zinc-500">
            &copy; {new Date().getFullYear()} JUS MEDIA. Built with Next.js & WordPress.
          </div>
        </footer>
      </body>
    </html>
  );
}
